version: "3"
services:
  dados-cnpj_db:
    build:
      dockerfile: ./docker/mysql.dockerfile
      context: .
    container_name: dados-cnpj_db
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=dadoscnpj
      - MYSQL_DATABASE=dados_cnpj
      - MYSQL_USER=dadoscnpj
      - MYSQL_PASSWORD=dadoscnpj
    command: ['mysqld', '--character-set-server=latin2', '--collation-server=latin2_general_ci']
    volumes:
      - cnpj_db:/var/lib/mysql
    networks:
      - dados_cnpj_net
    
  dados-cnpj:
    build:
      dockerfile: ./docker/dados_cnpj.dockerfile
      context: .
    image: dados-cnpj
    container_name: dados-cnpj
    volumes:
      - ./data:/app/data
    networks:
      - dados_cnpj_net
    depends_on:
      - "dados-cnpj_db"

networks:
  dados_cnpj_net:
    driver: bridge

volumes:
  cnpj_db:
    external: true